config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'blog', to: 'pages#blog'
  get 'be-of-service', to:'pages#be_of_service'
  get 'calendar', to: 'pages#calendar'
  get 'classes', to: 'events#classes'
  get 'give', to: 'pages#give'
  post 'registrations', to: 'events#create_registration'
  get 'venue', to: 'pages#venue'
  get 'who-we-are', to: 'pages#who_we_are'
  get 'youth', to: 'pages#youth'

  resources :events, only: [:index, :show]
  resources :groups, only: [:index]
  resources :prayer_requests, only: [:new, :create, :edit]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <div class="footer-contact">
      <h6>CONTACT US</h6>
      <div class= "contact-details" >
        <div class="footer-phone">
          <a href="tel:9702241206" class="foot-phone"> PHONE: (970) 224-1206</a>
        </div>
        <div class="footer-email">
          <a href="mailto:info.newthoughtnoco@gmail.com" class="foot-email"> EMAIL: info.newthoughtnoco@gmail.com</a>
        </div>
        <a href="https://www.facebook.com/NTNCCSL/" target= "_blank"><i class="fa fa-facebook"></i>FIND US ON FACEBOOK</a>
      </div>
      <div class="footer-admin">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        <% else %>
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="yam-footer">
    <%= link_to "http://www.amyhogue.com/", target: :_blank do %>
      <span>Powered By</span>
      <%= image_tag("yam.png")%>
      <span>Yam</span>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-ntnoco">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-ntnoco-brand" do %>
  <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-ntnoco-links hidden-xs hidden-sm">
    <!-- I'm New -->
    <div class="dropdown">
      <%= link_to "#", class: "navbar-ntnoco-item navbar-ntnoco-link dropdown-toggle navbar-ntnoco-menu", "data-toggle" => "dropdown" do %>
        About Us
        <span class="caret"></span>
      <% end %>
      <ul class="dropdown-menu dropdown-menu-right navbar-ntnoco-dropdown-menu">
        <li>
          <%= link_to "What We Do", about_path %>
        </li>
        <li>
          <%= link_to "Who We Are", "/who-we-are" %>
        </li>
      </ul>
    </div>

    <!-- Youth -->
    <div>
      <%= link_to "Youth", youth_path, class: "navbar-ntnoco-item navbar-ntnoco-link navbar-ntnoco-menu" %>
    </div>

    <!-- events -->
    <div class="dropdown">
      <%= link_to "#", class: "navbar-ntnoco-item navbar-ntnoco-link dropdown-toggle navbar-ntnoco-menu", "data-toggle" => "dropdown" do %>
        Be Connected
        <span class="caret"></span>
      <% end %>

      <ul class="dropdown-menu dropdown-menu-right navbar-ntnoco-dropdown-menu">
        <li>
          <%= link_to "Classes", classes_path %>
        </li>
        <li>
          <%= link_to "Events", events_path %>
        </li>
        <li>
          <%= link_to "Groups", groups_path %>
        </li>
        <li>
          <%= link_to "Church Calendar", calendar_path %>
        </li>
      </ul>
    </div>

    <!-- Be Inspired -->
    <div class="dropdown">
      <%= link_to "#", class: "navbar-ntnoco-item navbar-ntnoco-link dropdown-toggle navbar-ntnoco-menu", "data-toggle" => "dropdown" do %>
        Be Inspired
        <span class="caret"></span>
      <% end %>

      <ul class="dropdown-menu dropdown-menu-right navbar-ntnoco-dropdown-menu">
        <li>
          <%= link_to "Prayer Request", new_prayer_request_path %>
        </li>
        <li>
          <%= link_to "Inspiration Blog", blog_path %>
        </li>
      </ul>
    </div>

    <!-- Serve and Give -->
    <div class="dropdown">
      <%= link_to "#", class: "navbar-ntnoco-item navbar-ntnoco-link dropdown-toggle navbar-ntnoco-menu", "data-toggle" => "dropdown" do %>
      Be of Service
      <span class="caret"></span>
      <% end %>
      <ul class="dropdown-menu dropdown-menu-right navbar-ntnoco-dropdown-menu">
        <li>
          <%= link_to "Pastoral Care", be_of_service_path %>
        </li>
        <li>
          <%= link_to "Community Outreach", be_of_service_path(anchor: 'outreach') %>
        </li>
        <li>
          <%= link_to "Volunteering", be_of_service_path(anchor: 'volunteering') %>
        </li>
        <li>
          <%= link_to "Ways to Give", be_of_service_path(anchor: 'ways-to-give') %>
        </li>
      </ul>
    </div>

    <div>
      <%= link_to "Venue Rental", venue_path, class: "navbar-ntnoco-item navbar-ntnoco-link" %>
    </div>

    <div>
      <%= link_to give_path,  class: "btn btn-primary donate-btn navbar-ntnoco-item" do%>
      <p>DONATE</p>
      <% end %>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-mobile-dropdown hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle navbar-ntnoco-item" data-toggle="dropdown"></i>

      <ul class="dropdown-menu dropdown-menu-right navbar-ntnoco-dropdown-menu">
        <li class="dropdown-submenu">
          <%= link_to "#", class: 'dropdown-submenu-item' do %>
            About Us
            <span class="caret"></span>
          <% end %>

          <ul class="dropdown-menu">
            <li>
              <%= link_to "What We Do", about_path %>
            </li>
            <li>
              <%= link_to "Who We Are", "/who-we-are" %>
            </li>
          </ul>
        </li>

        <li>
          <%= link_to "Youth", youth_path %>
        </li>

        <li class="dropdown-submenu">
          <%= link_to "#", class: 'dropdown-submenu-item' do %>
            Be Connected
            <span class="caret"></span>
          <% end %>

          <ul class="dropdown-menu">
            <li>
              <%= link_to "Classes", classes_path %>
            </li>
            <li>
              <%= link_to "Events", events_path %>
            </li>
            <li>
              <%= link_to "Groups", groups_path %>
            </li>
            <li>
              <%= link_to "Church Calendar", calendar_path %>
            </li>
          </ul>
        </li>

        <li class="dropdown-submenu">
          <%= link_to "#", class: 'dropdown-submenu-item' do %>
            Be Inspired
            <span class="caret"></span>
          <% end %>

          <ul class="dropdown-menu">
            <li>
              <%= link_to "Prayer Request", new_prayer_request_path %>
            </li>
            <li>
              <%= link_to "Inspiration Blog", blog_path %>
            </li>
          </ul>
        </li>

        <li class="dropdown-submenu">
          <%= link_to "#", class: 'dropdown-submenu-item' do %>
            Be Of Service
            <span class="caret"></span>
          <% end %>

          <ul class="dropdown-menu">
            <li>
              <%= link_to "Pastoral Care", be_of_service_path %>
            </li>
            <li>
              <%= link_to "Community Outreach", be_of_service_path(anchor: 'outreach') %>
            </li>
            <li>
              <%= link_to "Volunteering", be_of_service_path(anchor: 'volunteering') %>
            </li>
            <li>
              <%= link_to "Ways to Give", be_of_service_path(anchor: 'ways-to-give') %>
            </li>
          </ul>
        </li>

        <li>
          <%= link_to "Venue Rental", venue_path %>
        </li>
        <li>
          <%= link_to "Make a Donation", give_path, class: 'hidden-sm dropdown-btn' %>
        </li>
      </ul>
    </div>

    <div class="hidden-xs">
      <%= link_to give_path,  class: "btn btn-primary donate-btn navbar-ntnoco-item" do %>
        <p>DONATE</p>
      <% end %>
    </div>
  </div>

</div>

app/views/shared/_secondary_navbar.html.erb
<div class="navbar-sticky navbar-filters">
  <% items.each do |item| %>
    <%= link_to item[:url] do %>
      <h4><%= item[:title] %></h4>
    <% end %>
  <% end %>
</div>